-- CreateEnum
CREATE TYPE "MysDesignation" AS ENUM ('PRESIDENT', 'SECRETARY', 'IMMEDIATE_PAST_PRESIDENT', 'PAST_PRESIDENT', 'PAST_SECRETARY', 'EXECUTIVE_MEMBER', 'JOINT_SECRETARY', 'INVITEES', 'VICE_PRESIDENT', 'TREASURER', 'ORGANIZATION_MINISTER');

-- AlterTable
ALTER TABLE "profiles" ADD COLUMN     "mysDesignation" "MysDesignation";
